version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: "Home Office"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  python_app:
    build:
      context: "./Data Entry"
    volumes:
      - "./Data Entry:/app"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_DATABASE: "Home Office"
    ports:
      - "5000:5000"

  java_app:
    build:
      context: "./Home Office Backend Java"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: "./frontend"
    ports:
      - "3000:3000"

volumes:
  db_data:
