# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import get_nav_pb2 as get__nav__pb2

GRPC_GENERATED_VERSION = "1.66.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in get_nav_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class get_navStub(object):
    """Service definition for GetNAV"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
            "/get_nav/GetData",
            request_serializer=get__nav__pb2.Request.SerializeToString,
            response_deserializer=get__nav__pb2.Response.FromString,
            _registered_method=True,
        )


class get_navServicer(object):
    """Service definition for GetNAV"""

    def GetData(self, request, context):
        """RPC method to get data"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_get_navServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetData": grpc.unary_unary_rpc_method_handler(
            servicer.GetData,
            request_deserializer=get__nav__pb2.Request.FromString,
            response_serializer=get__nav__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "get_nav", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("get_nav", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class get_nav(object):
    """Service definition for GetNAV"""

    @staticmethod
    def GetData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/get_nav/GetData",
            get__nav__pb2.Request.SerializeToString,
            get__nav__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
